nosana:
  description: Nosana-Node Pipeline
      
global:
  image: registry.hub.docker.com/library/golang:latest

  trigger:
    branch:
      - all

  environment:
    # Specify that apt will be used in noninteractive env. 
    # https://www.debian.org/releases/sarge/s390/ch05s02.html.en
    DEBIAN_FRONTEND: noninteractive

jobs:
  - name: install deps and build container
    commands:
      - pwd
      - go mod init example/hello # Initialize
      - touch hello.go
      - echo 'package main' >> hello.go
      - echo 'import "fmt"' >> hello.go
      - echo 'func main() { fmt.Println("Hello, World!") }' >> hello.go
      - echo >> hello.go
      - cat hello.go
      - go run hello.go
      - mkdir build
      - go build -o build/
    artifacts:
      - name: build
        path: ./build/

  - name: release
    commands:
      - ./build/hello
    resources:
      - build
