# .nosana-ci.yml
nosana:
    description: Build Nosana Documentation
    storage: IPFS

global:
    image: registry.hub.docker.com/library/node:18

    # Git, trigger on these branches
    trigger:
        branch:
            - main

    # Environment variables
    environment:
        APP_ENV: production # comment here about this var

    # Allow pipeline to stop if one job fails
    allow_failure: true # default: false

jobs:

    # Install dependencies
    - name: install
      commands:
        - yarn ci
      artifacts: # artifact for the next job
        - name: node_modules
          path: ./node_modules/

    # Lint and generate docs.
    - name: generate
      commands:
          - yarn run test
      resources: # artifact from previous job
        - node_modules
      artifacts: # artifact for deployment
          - name: dist
            path: ./dist/

    # Upload dist
    - name: ditribute
      commands:
        - yarn run upload
      resources:
        - dist

